/* SealPlatform/config.h.  Generated by configure.  */
// Looking for config.h but can't find it?  It is generated from this template
// and put under platform-specific includes in SEAL_X_Y_Z/$SCRAM_ARCH/include.

#ifndef SEAL_PLATFORM_CONFIG_H
# define SEAL_PLATFORM_CONFIG_H

#ifdef __linux__
#include "FWCore/PluginManager/interface/sysapi/platform_config_slc3_ia32_gcc323.h"
#endif
#ifdef __APPLE__
#include "FWCore/PluginManager/interface/sysapi/platform_config_osx_105_gcc401.h"
#endif
#endif /* SEAL_PLATFORM_CONFIG_H */
